# Header
menu:
  - title: Home
    url: /
    intro: "Homepage"
    icon: "fa fa-fire"
  - title: Archives
    url: /archives/
    intro: "Archives"
    icon: "fa fa-archive"

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
email: mailto