# Sidebar
widgets:
- about
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>Etiam porta <em>sem malesuada magna</em> mollis euismod.
  Cras mattis consectetur purus sit amet fermentum. Aenean
  lacinia bibendum nulla sed consectetur.</p>


# Miscellaneous
google_analytics: